Update workflows

diff --git a/.github/workflows/build-64.yml b/.github/workflows/build-64.yml
--- a/.github/workflows/build-64.yml
+++ b/.github/workflows/build-64.yml
@@ -39,7 +39,21 @@ jobs:
           .\build_fix.ps1
 
       - name: Generate Visual Studio Project Files
-        run: .\premake5.exe --os=windows --gmcommon=./garrysmod_common vs2022
+        shell: pwsh
+        run: |
+          $gmcommonPath = Get-ChildItem -Path $PWD -Directory -Recurse -Force |
+                          Where-Object { $_.Name -eq 'garrysmod_common' } |
+                          Select-Object -First 1
+
+          if (-not $gmcommonPath) {
+              Write-Error "garrysmod_common not found in any subfolder"
+              exit 1
+          }
+
+          $gmcommon = $gmcommonPath.FullName
+          Write-Host "Using garrysmod_common at $gmcommon"
+
+          .\premake5.exe --os=windows --gmcommon="$gmcommon" vs2022
 
       - name: Build 64-bit DLL
         run: |
